export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const SAVE_PREF_FAILED = 'SAVE_PREF_FAILED';
export const SAVE_PREF_SUCCESS = 'SAVE_PREF_SUCCESS';

export const GET_PREF_FAILED = 'GET_PREF_FAILED';
export const GET_PREF_SUCCESS = 'GET_PREF_SUCCESS';
